version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: myuserpassword
      POSTGRES_DB: local-discord-like
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  data-postgres:
